-- 예측 마켓 댓글 (배틀식: YES/NO 진영 + 좋아요) + 활동 포인트 연동
-- 2026-07-09 Management API로 원격 적용 (기록용)

create table if not exists public.market_comments (
  id         bigint generated by default as identity primary key,
  market_id  bigint not null references public.markets(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  side       text not null check (side in ('yes','no')),
  content    text not null,
  created_at timestamptz not null default now()
);
create index if not exists mkc_market_idx on public.market_comments (market_id, created_at desc);

create table if not exists public.market_comment_likes (
  comment_id bigint not null references public.market_comments(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

alter table public.market_comments enable row level security;
alter table public.market_comment_likes enable row level security;

drop policy if exists "mkc read" on public.market_comments;
create policy "mkc read" on public.market_comments for select using (true);
drop policy if exists "mkc insert self" on public.market_comments;
create policy "mkc insert self" on public.market_comments for insert with check (auth.uid() = user_id);
drop policy if exists "mkc delete self" on public.market_comments;
create policy "mkc delete self" on public.market_comments for delete using (auth.uid() = user_id);

drop policy if exists "mkcl read" on public.market_comment_likes;
create policy "mkcl read" on public.market_comment_likes for select using (true);
drop policy if exists "mkcl insert self" on public.market_comment_likes;
create policy "mkcl insert self" on public.market_comment_likes for insert with check (auth.uid() = user_id);
drop policy if exists "mkcl delete self" on public.market_comment_likes;
create policy "mkcl delete self" on public.market_comment_likes for delete using (auth.uid() = user_id);

-- 마켓 댓글도 활동 포인트 지급 (act_comment 상한 공유)
create or replace function public._pts_mkcomment() returns trigger
  language plpgsql security definer set search_path = public as $$
begin perform public._award(NEW.user_id, 20, 'act_comment', 15); return NEW; end $$;
drop trigger if exists trg_pts_mkcomment on public.market_comments;
create trigger trg_pts_mkcomment after insert on public.market_comments
  for each row execute function public._pts_mkcomment();

-- 대댓글 지원 (2026-07-09 추가)
alter table public.market_comments add column if not exists parent_id bigint references public.market_comments(id) on delete cascade;
create index if not exists mkc_parent_idx on public.market_comments(parent_id);
