-- 다중 선택지 마켓: 한 이벤트에 N개 후보(각 후보 = 독립 YES/NO CPMM)
-- 2026-07-09 Management API로 원격 적용 (기록용)

-- 1) 후보(outcome) 테이블
create table if not exists public.market_outcomes (
  id         bigint generated by default as identity primary key,
  market_id  bigint not null references public.markets(id) on delete cascade,
  label      text not null,
  image_url  text,
  sort_order int not null default 0,
  pool_yes   double precision not null default 1000,
  pool_no    double precision not null default 1000,
  is_winner  boolean,
  created_at timestamptz not null default now()
);
create index if not exists mo_market_idx on public.market_outcomes(market_id, sort_order);
alter table public.market_outcomes enable row level security;
drop policy if exists "mo read" on public.market_outcomes;
create policy "mo read" on public.market_outcomes for select using (true);

-- 2) markets: 타입 + 정산 후보
alter table public.markets add column if not exists market_type text not null default 'binary';
alter table public.markets add column if not exists resolved_outcome_id bigint;

-- 3) positions / trades → outcome 단위 (기존 비어있어 재생성)
drop table if exists public.market_trades cascade;
drop table if exists public.market_positions cascade;

create table public.market_positions (
  id         bigint generated by default as identity primary key,
  market_id  bigint not null references public.markets(id) on delete cascade,
  outcome_id bigint not null references public.market_outcomes(id) on delete cascade,
  user_id    uuid not null references auth.users(id) on delete cascade,
  yes_shares double precision not null default 0,
  no_shares  double precision not null default 0,
  spent      double precision not null default 0,
  unique (outcome_id, user_id)
);
create index positions_market_idx on public.market_positions(market_id);
create index positions_user_idx on public.market_positions(user_id);
alter table public.market_positions enable row level security;
create policy "positions read" on public.market_positions for select using (true);

create table public.market_trades (
  id         bigint generated by default as identity primary key,
  market_id  bigint not null references public.markets(id) on delete cascade,
  outcome_id bigint not null references public.market_outcomes(id) on delete cascade,
  user_id    uuid references auth.users(id) on delete set null,
  side       text not null check (side in ('yes','no')),
  spend      double precision not null,
  shares     double precision not null,
  price_yes  double precision not null,
  created_at timestamptz not null default now()
);
create index trades_market_idx on public.market_trades(market_id, created_at);
create index trades_outcome_idx on public.market_trades(outcome_id, created_at);
alter table public.market_trades enable row level security;
create policy "trades read" on public.market_trades for select using (true);

-- 파라미터 이름이 바뀐 함수는 교체 전 drop 필요
drop function if exists public.market_trade(bigint,text,double precision);
drop function if exists public.market_resolve(bigint,text);
drop function if exists public.create_market(text,text,text,text,timestamptz,double precision);

-- ============ create_market: 후보 배열 지원 ============
-- p_outcomes: jsonb 배열. null/1개 → binary(단일 예/아니오). 2개+ → multi.
--   예: [{"label":"하메네이"},{"label":"갈리바프"}]
create or replace function public.create_market(
  p_question text, p_description text, p_category text, p_image_url text,
  p_close_at timestamptz, p_outcomes jsonb default null, p_liquidity double precision default 1000
) returns bigint language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid(); v_id bigint; v_liq double precision;
  v_type text; v_n int; v_elem jsonb; v_i int := 0;
begin
  if v_user is null then raise exception 'unauthorized'; end if;
  if p_question is null or length(trim(p_question)) = 0 then raise exception 'question required'; end if;
  if p_close_at is null or p_close_at <= now() then raise exception 'close_at must be future'; end if;
  v_liq := greatest(coalesce(p_liquidity, 1000), 100);

  v_n := coalesce(jsonb_array_length(p_outcomes), 0);
  v_type := case when v_n >= 2 then 'multi' else 'binary' end;

  insert into markets (question, description, category, image_url, created_by, close_at, market_type, pool_yes, pool_no)
  values (trim(p_question), p_description, p_category, p_image_url, v_user, p_close_at, v_type, v_liq, v_liq)
  returning id into v_id;

  if v_type = 'binary' then
    insert into market_outcomes (market_id, label, sort_order, pool_yes, pool_no)
    values (v_id, '예/아니오', 0, v_liq, v_liq);
  else
    for v_elem in select * from jsonb_array_elements(p_outcomes) loop
      insert into market_outcomes (market_id, label, image_url, sort_order, pool_yes, pool_no)
      values (v_id, coalesce(v_elem->>'label','후보'), v_elem->>'image', v_i, v_liq, v_liq);
      v_i := v_i + 1;
    end loop;
  end if;

  return v_id;
end $$;

-- ============ market_trade: outcome 단위 CPMM ============
create or replace function public.market_trade(
  p_outcome_id bigint, p_side text, p_spend double precision
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_user uuid := auth.uid(); o record; m record; v_bal double precision; v_shares double precision;
  v_y double precision; v_n double precision; v_k double precision; v_price double precision;
begin
  if v_user is null then return jsonb_build_object('ok', false, 'reason', 'unauthorized'); end if;
  if p_side not in ('yes','no') then return jsonb_build_object('ok', false, 'reason', 'bad_side'); end if;
  if p_spend is null or p_spend <= 0 then return jsonb_build_object('ok', false, 'reason', 'bad_amount'); end if;

  select * into o from market_outcomes where id = p_outcome_id for update;
  if o is null then return jsonb_build_object('ok', false, 'reason', 'not_found'); end if;
  select * into m from markets where id = o.market_id for update;
  if m.resolved or m.status <> 'open' or m.close_at <= now() then
    return jsonb_build_object('ok', false, 'reason', 'closed');
  end if;

  insert into point_balances (user_id) values (v_user) on conflict (user_id) do nothing;
  select balance into v_bal from point_balances where user_id = v_user for update;
  if v_bal < p_spend then return jsonb_build_object('ok', false, 'reason', 'insufficient', 'balance', v_bal); end if;

  v_y := o.pool_yes; v_n := o.pool_no; v_k := v_y * v_n;
  if p_side = 'yes' then
    v_shares := v_y + p_spend - (v_k / (v_n + p_spend));
    v_y := v_k / (v_n + p_spend); v_n := v_n + p_spend;
  else
    v_shares := v_n + p_spend - (v_k / (v_y + p_spend));
    v_n := v_k / (v_y + p_spend); v_y := v_y + p_spend;
  end if;
  v_price := v_n / (v_y + v_n);

  update market_outcomes set pool_yes = v_y, pool_no = v_n where id = p_outcome_id;
  update markets set volume = volume + p_spend where id = m.id;

  update point_balances set balance = balance - p_spend, updated_at = now() where user_id = v_user;
  insert into point_ledger (user_id, delta, reason, market_id) values (v_user, -p_spend, 'trade', m.id);

  insert into market_positions (market_id, outcome_id, user_id, yes_shares, no_shares, spent)
  values (m.id, p_outcome_id, v_user,
          case when p_side='yes' then v_shares else 0 end,
          case when p_side='no'  then v_shares else 0 end, p_spend)
  on conflict (outcome_id, user_id) do update set
    yes_shares = market_positions.yes_shares + (case when p_side='yes' then v_shares else 0 end),
    no_shares  = market_positions.no_shares  + (case when p_side='no'  then v_shares else 0 end),
    spent      = market_positions.spent + p_spend;

  insert into market_trades (market_id, outcome_id, user_id, side, spend, shares, price_yes)
  values (m.id, p_outcome_id, v_user, p_side, p_spend, v_shares, v_price);

  return jsonb_build_object('ok', true, 'shares', v_shares, 'price_yes', v_price, 'balance', v_bal - p_spend);
end $$;

-- ============ market_resolve: 이진(yes/no) / 다중(승리 후보) ============
create or replace function public.market_resolve(
  p_market_id bigint, p_outcome_id bigint default null, p_side text default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_user uuid := auth.uid(); m record; oc record; pos record; v_pay double precision; v_cnt int := 0;
begin
  if v_user is null then return jsonb_build_object('ok', false, 'reason', 'unauthorized'); end if;
  select * into m from markets where id = p_market_id for update;
  if m is null then return jsonb_build_object('ok', false, 'reason', 'not_found'); end if;
  if m.created_by <> v_user then return jsonb_build_object('ok', false, 'reason', 'forbidden'); end if;
  if m.resolved then return jsonb_build_object('ok', false, 'reason', 'already'); end if;

  if m.market_type = 'binary' then
    if p_side not in ('yes','no') then return jsonb_build_object('ok', false, 'reason', 'bad_side'); end if;
    select * into oc from market_outcomes where market_id = p_market_id limit 1;
    -- 단일 후보: 맞은 쪽 셰어 지급
    for pos in select user_id, yes_shares, no_shares from market_positions where outcome_id = oc.id loop
      v_pay := case when p_side='yes' then pos.yes_shares else pos.no_shares end;
      if v_pay > 0 then
        insert into point_balances (user_id) values (pos.user_id) on conflict (user_id) do nothing;
        update point_balances set balance = balance + v_pay, updated_at = now() where user_id = pos.user_id;
        insert into point_ledger (user_id, delta, reason, market_id) values (pos.user_id, v_pay, 'payout', p_market_id);
        v_cnt := v_cnt + 1;
      end if;
    end loop;
    update market_outcomes set is_winner = (p_side='yes') where id = oc.id;
    update markets set resolved = true, resolved_at = now(), status = 'resolved', outcome = p_side where id = p_market_id;
  else
    -- 다중: 승리 후보는 YES 지급, 나머지 후보는 NO 지급
    if p_outcome_id is null then return jsonb_build_object('ok', false, 'reason', 'need_outcome'); end if;
    if not exists (select 1 from market_outcomes where id = p_outcome_id and market_id = p_market_id) then
      return jsonb_build_object('ok', false, 'reason', 'bad_outcome');
    end if;
    for pos in select mp.user_id, mp.outcome_id, mp.yes_shares, mp.no_shares
               from market_positions mp where mp.market_id = p_market_id loop
      v_pay := case when pos.outcome_id = p_outcome_id then pos.yes_shares else pos.no_shares end;
      if v_pay > 0 then
        insert into point_balances (user_id) values (pos.user_id) on conflict (user_id) do nothing;
        update point_balances set balance = balance + v_pay, updated_at = now() where user_id = pos.user_id;
        insert into point_ledger (user_id, delta, reason, market_id) values (pos.user_id, v_pay, 'payout', p_market_id);
        v_cnt := v_cnt + 1;
      end if;
    end loop;
    update market_outcomes set is_winner = (id = p_outcome_id) where market_id = p_market_id;
    update markets set resolved = true, resolved_at = now(), status = 'resolved', resolved_outcome_id = p_outcome_id where id = p_market_id;
  end if;

  return jsonb_build_object('ok', true, 'paid_users', v_cnt);
end $$;

revoke all on function public.create_market(text,text,text,text,timestamptz,jsonb,double precision) from public, anon;
revoke all on function public.market_trade(bigint,text,double precision) from public, anon;
revoke all on function public.market_resolve(bigint,bigint,text) from public, anon;
grant execute on function public.create_market(text,text,text,text,timestamptz,jsonb,double precision) to authenticated;
grant execute on function public.market_trade(bigint,text,double precision) to authenticated;
grant execute on function public.market_resolve(bigint,bigint,text) to authenticated;

-- 옛 시그니처 정리 (market_trade는 동일 시그니처라 in-place 교체됨 → drop 금지)
drop function if exists public.create_market(text,text,text,text,timestamptz,double precision);
drop function if exists public.market_resolve(bigint,text);

-- 위 drop table ... cascade 로 predict_god_leaderboard 뷰가 함께 삭제되므로 재생성
create or replace view public.predict_god_leaderboard as
select
  m.created_by as user_id, up.nickname, up.level,
  count(distinct m.id) as markets_created,
  round(coalesce(sum(m.volume),0)::numeric,0) as total_volume,
  coalesce((select count(distinct mp.user_id) from public.market_positions mp
            join public.markets m2 on m2.id = mp.market_id
            where m2.created_by = m.created_by),0) as participants
from public.markets m
left join public.user_profiles up on up.user_id = m.created_by
where m.created_by is not null
group by m.created_by, up.nickname, up.level;
grant select on public.predict_god_leaderboard to anon, authenticated;
