-- 북마크(Save 갈라) 테이블 + follows 공개 조회 정책
-- 2026-07-08: Management API로 원격 DB에 이미 적용됨 (기록용)

create table if not exists public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  issue_id bigint not null references public.issues(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, issue_id)
);

alter table public.bookmarks enable row level security;

drop policy if exists "Users read own bookmarks" on public.bookmarks;
create policy "Users read own bookmarks" on public.bookmarks
  for select using (auth.uid() = user_id);

drop policy if exists "Users add bookmarks" on public.bookmarks;
create policy "Users add bookmarks" on public.bookmarks
  for insert with check (auth.uid() = user_id);

drop policy if exists "Users remove bookmarks" on public.bookmarks;
create policy "Users remove bookmarks" on public.bookmarks
  for delete using (auth.uid() = user_id);

-- 기존 정책(follower = auth.uid())은 팔로워 수 집계를 막아 항상 0이 나오던 버그 원인
drop policy if exists "Users read their follow data" on public.follows;
drop policy if exists "Follows are public" on public.follows;
create policy "Follows are public" on public.follows
  for select using (true);
