-- 여행 장소 지역(admin1) 정리 — 외국어·현지어 지역명을 한국어로, 좌표가 나라 밖인 곳은 내림(26.9.18 사장님 「태국어 동네 이름도 알맞은 지역으로 정리해」「다른 나라도 체크」)
-- 실측: 외국어 admin1 362종·1,525곳(88개국) + 광역 없음·외국어 도시 25곳. 같은 지역이 Normandie/Normandy/노르망디로 쪼개져 있었다.
-- ⚠️ 주변 장소 투표(kNN)는 경계에서 틀려(서플랑드르→에노주, 옥시타니→누벨아키텐) 쓰지 않았다. 이름 번역이라 장소가 속한 지역은 안 바뀐다.

-- 1) 백업(되돌리기용)
create table if not exists travel_places_admin1_backup_20260918 as
  select id, country_code, admin1, city, status, now() backed_at from travel_places
   where scale='spot' and country_code<>'KR' and (admin1 !~ '[가-힣]' or (admin1 is null and coalesce(city,'') !~ '[가-힣]'));
insert into travel_places_admin1_backup_20260918
  select p.id, p.country_code, p.admin1, p.city, p.status, now() from travel_places p
   where p.id in ('03eace56-b34c-4842-a517-93ae2899a1a6','07e95916-94db-410f-9fc6-acebd3ecaae8','0f4776d0-aabc-4949-9fe9-1ceeb31c7076','1188ad16-df11-414c-9532-ddb39e8b6650','2c304695-e2bf-4475-9cb5-2e504c1e9bca','3335ceee-647a-4bcb-b8ec-1ee2d3814618','4c083055-0205-4fe8-924c-ef7a9bc88e2b','5031e355-e0b4-4d52-a41c-458029c5727d','56b84918-d313-4a66-bc66-5aa9bedaba4c','66543dea-aa00-471b-b19b-d1e329318d4a','6c7c33b6-d954-4f01-808e-617f2565dff1','6e6c6290-2847-4bf6-a356-76287e491563','72effb4b-1907-42b4-a60f-6f307d36c990','832b7f11-732f-488f-8fd2-cde0911571f8','929f5f8f-cebc-4e02-9880-51705a42beb0','986dd84b-8935-4726-b802-deadefde0283','9c33b4a2-52a9-4cc5-ba28-60f28ece8f32','acab2e99-dbf0-46b0-97e3-edf772bcb1be','b018c07f-9de4-47cb-a98f-16ca60abb99f','b4e9eec3-9697-4652-9f6a-3e9c9110a070','b5303a42-2629-4ee2-8c7e-9c5105862e21','d336fbda-636f-42c9-99a8-04c4a9ec825d','dd259adc-c3c9-4055-b2bf-5ad72a5c2839','ea1d98de-f669-4b34-ba23-f7d49527769c','ec844c3c-aa9c-4f0b-84a4-4ef6434e9f28','f2a5699d-b18b-4491-a394-0f4de387c02a','f5142e33-cf1f-4619-b863-8197c00959f5')
     and not exists (select 1 from travel_places_admin1_backup_20260918 b where b.id=p.id);

-- 2) 이름표 — 앞으로 들어오는 장소도 이 표로 바뀐다(아래 트리거)
create table if not exists travel_admin1_alias (
  country_code text not null, raw text not null, ko text not null,
  primary key (country_code, raw));
alter table travel_admin1_alias enable row level security;
insert into travel_admin1_alias(country_code, raw, ko) values
('AR','Autonomous City of Buenos Aires','부에노스아이레스'),
('AR','Ciudad Autónoma de Buenos Aires','부에노스아이레스'),
('AR','Misiones','미시오네스주'),
('AR','Salta','살타주'),
('AR','Chubut','추부트주'),
('AR','Mendoza','멘도사주'),
('AR','Jujuy','후후이주'),
('AU','New South Wales','뉴사우스웨일스주'),
('AU','Queensland','퀸즐랜드주'),
('AU','Western Australia','웨스턴오스트레일리아주'),
('AU','South Australia','사우스오스트레일리아주'),
('AU','Tasmania','태즈메이니아주'),
('AZ','Qaradağ rayonu','바쿠'),
('AZ','Karadag Raion','바쿠'),
('BE','West-Vlaanderen','베스트플란데런주'),
('BE','Région de Bruxelles-Capitale - Brussels Hoofdstedelijk Gewest','브뤼셀 수도권 지역'),
('BE','Luxembourg','뤽상부르주'),
('BE','Antwerpen','안트베르펜'),
('BE','Antwerp','안트베르펜'),
('BF','Poni','포니주'),
('BG','Stara Zagora','스타라자고라'),
('BG','Sofia-City','소피아시주'),
('BO','Potosí','포토시주'),
('BO','La Paz','라파스'),
('BO','Santa Cruz','산타크루스주'),
('BO','Cochabamba','코차밤바주'),
('BO','Oruro','오루로주'),
('BO','Chuquisaca','추키사카주'),
('BO','Antofagasta Region','안토파가스타주'),
('BR','Misiones','미시오네스주'),
('BT','ཐིམ་ཕུ་རྫོང་ཁག་','팀부현'),
('BT','Thimphu District','팀부현'),
('BT','Paro District','파로현'),
('BT','དབང་འདུས་ཕོ་བྲང་རྫོང་ཁག་','왕듀포드랑현'),
('BT','སྤ་རོ་རྫོང་ཁག་','파로현'),
('BT','བཀྲ་ཤིས་སྒང་རྫོང་ཁག་','트라시강현'),
('BT','བུམ་ཐང་རྫོང་ཁག་','붐탕현'),
('BT','Chukha','추카현'),
('BW','Chobe District','초베구'),
('BY','Mahilyow Region','마힐료우주'),
('BY','Vitsebsk Region','비쳅스크주'),
('BZ','Belize District','벨리즈구'),
('BZ','Toledo','톨레도구'),
('CH','Grand Est','바젤슈타트'),
('CI','Montagnes','몽타뉴구'),
('CL','Región del Libertador General Bernardo O''Higgins','리베르타도르헤네랄베르나르도오이긴스주'),
('CL','Antofagasta Region','안토파가스타주'),
('CL','Aysen del General Carlos Ibanez del Campo Region','아이센주'),
('CL','Región Aysén del General Carlos Ibáñez del Campo','아이센주'),
('CL','Araucania Region','아라우카니아주'),
('CL','Valparaiso Region','발파라이소주'),
('CN','Amur Oblast','헤이룽장성'),
('CO','Antioquia','안티오키아주'),
('CO','Bogota, Capital District','보고타'),
('CO','Bolívar','볼리바르주'),
('CO','Magdalena','막달레나주'),
('CO','RAP Caribe','볼리바르주'),
('CO','Cundinamarca','쿤디나마르카주'),
('CO','Amazonas','아마소나스주'),
('CO','Meta','메타주'),
('CO','Quindío','킨디오주'),
('CO','Boyacá','보야카주'),
('CO','Valle del Cauca','바예델카우카주'),
('CO','Huila','우일라주'),
('CR','Puntarenas','푼타레나스'),
('CR','Naso Tjër Di','나소 치에르 디'),
('CU','La Habana','아바나'),
('CU','Sancti Spiritus','상크티스피리투스주'),
('CU','Cienfuegos','시엔푸에고스주'),
('CU','Santiago de Cuba','산티아고데쿠바'),
('CZ','Jihomoravský kraj','남모라바주'),
('CZ','South Bohemian Region','남보헤미아주'),
('CZ','South Moravian Region','남모라바주'),
('CZ','Kraj Vysočina','비소치나주'),
('CZ','Central Bohemian Region','중앙보헤미아주'),
('CZ','Zlín Region','즐린주'),
('CZ','Liberec Region','리베레츠주'),
('CZ','Olomouc Region','올로모우츠주'),
('CZ','Pardubický kraj','파르두비체주'),
('DO','Distrito Nacional','국가 지구'),
('DO','Santo Domingo','산토도밍고'),
('EC','Chimborazo','침보라소주'),
('EC','Pichincha','피친차주'),
('EC','Guayas','과야스주'),
('EE','Harju County','하리우주'),
('ES','Community of Madrid','마드리드 지방'),
('ES','Comunidad de Madrid','마드리드 지방'),
('ES','Aragón','아라곤주'),
('ES','Aragon','아라곤주'),
('ES','Valencian Community','발렌시아주'),
('ES','Comunitat Valenciana','발렌시아주'),
('ES','Autonomous Community of the Basque Country','바스크 지방'),
('ES','Canary Islands','카나리아 제도'),
('ES','Canarias','카나리아 제도'),
('ES','Navarre','나바라 지방'),
('ES','Navarra','나바라 지방'),
('ES','Extremadura','에스트레마두라 지방'),
('ES','Castilla-La Mancha','카스티야라만차 지방'),
('FI','Uusimaa','우시마 지역'),
('FI','Lapland','라피 지역'),
('FI','Satakunta','사타쿤타 지역'),
('FJ','Central','중부 지방'),
('FJ','Eastern','동부 지방'),
('FJ','Western','서부 지방'),
('FM','Chuuk','추크주'),
('FM','Kosrae','코스라에주'),
('FO','Vágar region','바가르'),
('FO','Norðoyar region','노르되이아르'),
('FR','Hauts-de-France','오드프랑스'),
('FR','Grand Est','그랑테스트'),
('FR','Provence-Alpes-Côte d''Azur','프로방스알프코트다쥐르'),
('FR','Occitania','옥시타니'),
('FR','Occitanie','옥시타니'),
('FR','Centre-Val de Loire','상트르발드루아르'),
('FR','Normandie','노르망디'),
('FR','Normandy','노르망디'),
('FR','Aragón','아라곤주'),
('GE','Gauteng','하우텡주'),
('GR','Region of Crete','크레타주'),
('GR','Περιφέρεια Κρήτης','크레타주'),
('GR','Περιφέρεια Θεσσαλίας','테살리아주'),
('GR','Thessaly','테살리아주'),
('GR','Central Macedonia','중앙마케도니아주'),
('GR','Περιφέρεια Κεντρικής Μακεδονίας','중앙마케도니아주'),
('GR','Central Greece','중앙그리스'),
('GT','Sacatepéquez','사카테페케스주'),
('GT','Izabal','이사발주'),
('GT','Guatemala Department','과테말라주'),
('GT','Petén','페텐주'),
('GT','Sololá','솔롤라주'),
('GT','Quiché','키체주'),
('GU','Guam','괌'),
('HN','Copán','코판주'),
('HR','Split-Dalmatia County','스플리트달마티아주'),
('HR','Splitsko-dalmatinska županija','스플리트달마티아주'),
('HR','Zadar County','자다르주'),
('HR','Zadarska županija','자다르주'),
('HR','Dubrovačko-neretvanska županija','두브로브니크네레트바주'),
('HR','Istria County','이스트라주'),
('HR','Lika-Senj County','리카센주'),
('HT','Département du Nord','노르주'),
('HU','Central Hungary','중부 헝가리'),
('HU','Közép-Magyarország','중부 헝가리'),
('HU','Alföld és Észak','대평원·북부 헝가리'),
('HU','Great Plain and North','대평원·북부 헝가리'),
('HU','Transdanubia','트란스다누비아'),
('HU','Dunántúl','트란스다누비아'),
('IE','Leinster','렌스터'),
('IE','County Galway','골웨이주'),
('IE','Connacht','코노트'),
('IE','Munster','먼스터'),
('IL','מחוז הצפון','북부구'),
('IL','North District','북부구'),
('IS','Southern Region','쉬뒤를란드'),
('IS','Þingeyjarsveit','노르뒤를란드 에이스트라'),
('IS','Capital Region','회뷔드보르가르스바이디'),
('IS','Mýrdalshreppur','쉬뒤를란드'),
('IS','Múlaþing','아우스튀를란드'),
('IS','Bláskógabyggð','쉬뒤를란드'),
('IS','Hrunamannahreppur','쉬뒤를란드'),
('IS','Northeastern Region','노르뒤를란드 에이스트라'),
('IS','Sveitarfélagið Hornafjörður','아우스튀를란드'),
('JM','Cornwall County','콘월주'),
('JM','Portland','포틀랜드구'),
('JM','Surrey County','서리주'),
('JM','Saint James','세인트제임스구'),
('JM','Middlesex County','미들섹스주'),
('KE','Lamu','라무'),
('KH','Battambang','바탐방'),
('KH','Tbong Khmum','트봉크뭄주'),
('KH','ខេត្តព្រះវិហារ','프레아비헤아르주'),
('KZ','Jetisu Region','제티수주'),
('LB','Keserwan-Jbeil Governorate','케세르완주베일주'),
('LK','Central Province','중부주'),
('LK','Western Province','서부주'),
('LK','Southern Province','남부주'),
('LK','Uva Province','우바주'),
('LK','North Central Province','북중부주'),
('LK','Sabaragamuwa Province','사바라가무와주'),
('LK','Eastern Province','동부주'),
('LS','KwaZulu-Natal','콰줄루나탈주'),
('LV','Брэсцкая вобласць','브레스트주'),
('MA','Marrakech-Safi','마라케시사피 지방'),
('MA','Marrakech-Safi ⵎⵕⵕⴰⴽⵛ-ⴰⵙⴼⵉ مراكش-أسفي','마라케시사피 지방'),
('MA','Fez-Meknes','페스메크네스 지방'),
('MA','Fès-Meknès ⴼⴰⵙ-ⵎⴽⵏⴰⵙ فاس-مكناس','페스메크네스 지방'),
('MA','Drâa-Tafilalet','드라타필랄레트 지방'),
('MA','Drâa-Tafilalet ⴷⴰⵔⵄⴰ-ⵜⴰⴼⵉⵍⴰⵍⵜ درعة تافيلالت','드라타필랄레트 지방'),
('MA','Casablanca-Settat','카사블랑카세타트 지방'),
('MA','Casablanca-Settat ⵜⴰⴷⴷⴰⵔⵜ ⵜⵓⵎⵍⵉⵍⵜ-ⵙⵟⵟⴰⵜ الدار البيضاء-سطات','카사블랑카세타트 지방'),
('MA','Rabat-Salé-Kénitra ⵔⴱⴰⵟ-ⵙⵍⴰ-ⵇⵏⵉⵟⵔⴰ الرباط-سلا-القنيطرة','라바트살레케니트라 지방'),
('MA','Rabat-Salé-Kénitra','라바트살레케니트라 지방'),
('MA','Souss-Massa','수스마사 지방'),
('MA','Tanger-Tétouan-Al Hoceïma ⵟⴰⵏⵊ-ⵟⵉⵜⴰⵡⵉⵏ-ⵍⵃⵓⵙⵉⵎⴰ طنجة تطوان الحسيمة','탕헤르테투안알호세이마 지방'),
('ME','Kotor Municipality','코토르 지방 자치제'),
('MP','Northern Mariana Islands','북마리아나 제도'),
('MW','Mangochi','망고치현'),
('MX','Mexico City','멕시코시티'),
('MX','Ciudad de México','멕시코시티'),
('MX','Jalisco','할리스코주'),
('MX','Quintana Roo','킨타나로오주'),
('MX','Oaxaca','오아하카주'),
('MX','Yucatán','유카탄주'),
('MX','State of Mexico','멕시코주'),
('MX','Estado de México','멕시코주'),
('MX','Chiapas','치아파스주'),
('MX','Hidalgo','이달고주'),
('MX','San Luis Potosí','산루이스포토시주'),
('MX','Sonora','소노라주'),
('MX','Baja California','바하칼리포르니아주'),
('MX','Puebla','푸에블라주'),
('MX','Querétaro','케레타로주'),
('MX','Zacatecas','사카테카스주'),
('MX','Michoacán','미초아칸주'),
('MX','Veracruz','베라크루스주'),
('MX','Sinaloa','시날로아주'),
('MX','Guerrero','게레로주'),
('MX','Guanajuato','과나후아토주'),
('MX','Baja California Sur','바하칼리포르니아수르주'),
('MX','Campeche','캄페체주'),
('MX','Nuevo León','누에보레온주'),
('NC','Province Sud','남부주'),
('NC','Province des îles Loyauté','로열티 제도주'),
('NI','León','레온'),
('NO','Finnmark','핀마르크주'),
('NO','Nordland','노를란주'),
('NO','Nordenskiöld Land','스발바르제도-얀마웬섬'),
('NZ','Bay of Plenty','베이오브플렌티 지방'),
('NZ','Southland','사우스랜드 지방'),
('NZ','Manawatū-Whanganui','마너와투왕거누이 지방'),
('NZ','Otago','오타고 지방'),
('NZ','Canterbury','캔터베리 지방'),
('NZ','Waikato','와이카토 지방'),
('PA','Colón','콜론주'),
('PA','Provincia de Panamá','파나마주'),
('PE','Cusco','쿠스코'),
('PE','Lima','리마'),
('PE','Ica','이카'),
('PE','Ancash','앙카시주'),
('PE','La Libertad','라리베르타드주'),
('PE','Arequipa','아레키파주'),
('PE','Cajamarca','카하마르카'),
('PE','Junín','후닌주'),
('PE','Loreto','로레토주'),
('PE','Apurímac','아푸리막주'),
('PG','Oro','오로주'),
('PT','Lisbon','리스본'),
('PT','Lisboa','리스본'),
('PT','Guarda','구아르다'),
('PT','Aveiro','아베이루'),
('PT','Faro','파루'),
('PT','Braga','브라가'),
('PT','Leiria','레이리아'),
('PT','Santarém','산타렝'),
('PT','Viana do Castelo','비아나두카스텔루'),
('PT','Bragança','브라간사현'),
('PT','Setúbal','세투발'),
('PY','Distrito Capital','아순시온'),
('RO','Brașov','브라쇼브주'),
('RO','Sibiu','시비우주'),
('RO','Prahova','프라호바주'),
('RO','Tulcea','툴체아'),
('RO','Maramureș','마라무레슈주'),
('RO','Alba','알바주'),
('RO','Hunedoara','후네도아라'),
('RS','Централна Србија','중앙세르비아'),
('RU','Moscow','모스크바'),
('RU','Москва','모스크바'),
('RU','Дагестан','다게스탄 공화국'),
('RU','Dagestan','다게스탄 공화국'),
('RU','Kamchatka Krai','캄차카 변경주'),
('RU','Камчатский край','캄차카 변경주'),
('RU','Sakha Republic','사하 공화국'),
('RU','Республика Саха (Якутия)','사하 공화국'),
('RU','Архангельская область','아르한겔스크주'),
('RU','Khabarovsk Krai','하바롭스크 변경주'),
('RU','Владимирская область','블라디미르주'),
('RU','Rostov Oblast','로스토프주'),
('RU','Yamalo-Nenets Autonomous Okrug','야말로네네츠 자치구'),
('RU','Krasnoyarsk Krai','크라스노야르스크 지방'),
('RU','Omsk Oblast','옴스크주'),
('RU','Irkutsk Oblast','이르쿠츠크주'),
('RU','Севастополь','세바스토폴'),
('RU','Buryatia','부랴트 공화국'),
('RU','Kemerovo Oblast–Kuzbass','케메로보주'),
('RU','Карелия','카렐리야 공화국'),
('SC','Praslin','프라슬랭섬'),
('SC','La Digue Group','라디그섬'),
('SD','River Nile State','나일강주'),
('SD','الولاية الشمالية Northern State','북부주'),
('SE','Stockholms län','스톡홀름주'),
('SE','Stockholm County','스톡홀름주'),
('SE','Norrbottens län','노르보텐주'),
('SE','Norrbotten County','노르보텐주'),
('SE','Dalarnas län','달라르나주'),
('SK','Region of Bratislava','브라티슬라바주'),
('SK','Košický kraj','코시체주'),
('SK','Banskobystrický kraj','반스카비스트리차주'),
('SK','Žilinský kraj','질리나주'),
('SL','Kenema District','케네마구'),
('SO','Woqooyi Galbeed','워코이갈베드주'),
('SS','Pibor بيبور','피보르'),
('SV','La Libertad','라리베르타드주'),
('TD','Ennedi Ouest إنيدي الغربية','서엔네디주'),
('TH','ท่าตลาด','방콕'),
('TH','ยายชา','방콕'),
('TH','Tha Talat','방콕'),
('TJ','Вилояти Хатлон','하틀론주'),
('TL','Dili','딜리'),
('TO','ʻEua','에우아'),
('TR','Antalya','안탈리아'),
('TR','Izmir','이즈미르'),
('TR','İzmir','이즈미르'),
('TR','Nevşehir','네브셰히르'),
('TR','Ankara','앙카라'),
('TR','Konya','코니아'),
('TR','Aydın','아이든주'),
('TR','Van','반'),
('TR','Diyarbakır','디야르바크르'),
('TR','Gaziantep','가지안테프'),
('TR','Kars','카르스'),
('TR','Mardin','마르딘'),
('TR','Muğla','물라주'),
('TR','Adıyaman','아디야만'),
('TR','Sivas','시바스'),
('TR','Trabzon','트라브존'),
('TR','Edirne','에디르네'),
('TR','Mersin','메르신'),
('TR','Çorum','초룸'),
('TR','Canakkale','차나칼레주'),
('TR','Adana','아다나'),
('TR','Ardahan','아르다한주'),
('TT','Tobago','토바고섬'),
('TT','San Juan-Laventille','산후안라벤틸 지역'),
('TT','Sangre Grande','상그레그란데 지역'),
('TT','Tunapuna-Piarco','투나푸나피아르코 지역'),
('TZ','Coastal Zone','다르에스살람주'),
('TZ','Songwe Region','송웨주'),
('UG','Central Region','중부주'),
('UG','Kanungu','카눙구구'),
('UG','Eastern Region','동부주'),
('UG','Kasese','카세세구'),
('UG','Rubanda','루반다구'),
('US','District of Columbia','워싱턴 D.C.'),
('UZ','Yunusabad district','타슈켄트'),
('UZ','Yakkasaray District','타슈켄트'),
('UZ','Chilonzor Tumani','타슈켄트'),
('UZ','Mirzo Ulugbek district','타슈켄트'),
('UZ','Olmazor Tumani','타슈켄트'),
('UZ','Yashnobod Tumani','타슈켄트'),
('UZ','Вилояти Суғд','수그드주'),
('UZ','Жетісу облысы','제티수주'),
('VE','Falcón','팔콘주'),
('VE','Capital District','수도 지구'),
('VN','Phường Hóa Châu','후에'),
('VN','Phường Kim Long','후에'),
('VN','Phường Thuận Hóa','후에'),
('VU','Tafea','타페아주'),
('VU','Malampa','말람파주'),
('VU','Sanma','산마주'),
('ZA','Gauteng','하우텡주'),
('ZA','KwaZulu-Natal','콰줄루나탈주')
on conflict (country_code, raw) do update set ko = excluded.ko;

update travel_places p set admin1 = a.ko
  from travel_admin1_alias a
 where a.country_code = p.country_code and a.raw = p.admin1;

-- 3) 광역이 비고 도시만 외국어인 곳
update travel_places p set admin1 = v.ko
  from (values ('AR','Ushuaia','티에라델푸에고주'),
('AU','Cairns','퀸즐랜드주'),
('AZ','Ismayilli','이스마일리구'),
('BN','Bandar Seri Begawan','브루나이무아라구'),
('BO','Puno','라파스'),
('CI','Grand-Lahou','라귄 지구'),
('CV','Pedra de Lume','살섬'),
('GL','Oqaatsut','아바나타'),
('LV','Vaide','쿠르제메'),
('MK','Ohrid','오흐리드'),
('MT','Manikata','몰타 북부'),
('MY','Langkawi','크다주'),
('OM','Sur','남샤르키야주'),
('PE','Paracas','이카'),
('PE','Puno','푸노주'),
('PT','Lisbon','리스본'),
('QA','Khor Al Adaid','알와크라'),
('SI','Veliki Otok','포스토이나'),
('TW','Kaohsiung','가오슝'),
('VA','Vatican City','바티칸 시국'),
('VN','Cán Tỷ Commune','하장성'),
('XK','Reka e Allages','페야구')) v(cc, city, ko)
 where p.admin1 is null and p.country_code = v.cc and p.city = v.city and p.scale='spot';

-- 4) 좌표가 자기 나라 밖(동명의 엉뚱한 곳으로 찍힘) → 지도·목록에서 내림
update travel_places set status = 'pending'
 where status='live' and id in ('03eace56-b34c-4842-a517-93ae2899a1a6','07e95916-94db-410f-9fc6-acebd3ecaae8','0f4776d0-aabc-4949-9fe9-1ceeb31c7076','1188ad16-df11-414c-9532-ddb39e8b6650','2c304695-e2bf-4475-9cb5-2e504c1e9bca','3335ceee-647a-4bcb-b8ec-1ee2d3814618','4c083055-0205-4fe8-924c-ef7a9bc88e2b','5031e355-e0b4-4d52-a41c-458029c5727d','56b84918-d313-4a66-bc66-5aa9bedaba4c','66543dea-aa00-471b-b19b-d1e329318d4a','6c7c33b6-d954-4f01-808e-617f2565dff1','6e6c6290-2847-4bf6-a356-76287e491563','72effb4b-1907-42b4-a60f-6f307d36c990','832b7f11-732f-488f-8fd2-cde0911571f8','929f5f8f-cebc-4e02-9880-51705a42beb0','986dd84b-8935-4726-b802-deadefde0283','9c33b4a2-52a9-4cc5-ba28-60f28ece8f32','acab2e99-dbf0-46b0-97e3-edf772bcb1be','b018c07f-9de4-47cb-a98f-16ca60abb99f','b4e9eec3-9697-4652-9f6a-3e9c9110a070','b5303a42-2629-4ee2-8c7e-9c5105862e21','d336fbda-636f-42c9-99a8-04c4a9ec825d','dd259adc-c3c9-4055-b2bf-5ad72a5c2839','ea1d98de-f669-4b34-ba23-f7d49527769c','ec844c3c-aa9c-4f0b-84a4-4ef6434e9f28','f2a5699d-b18b-4491-a394-0f4de387c02a','f5142e33-cf1f-4619-b863-8197c00959f5');

-- 5) 트리거: 수집기가 외국어 admin1 을 넣어도 이름표에 있으면 한국어로
create or replace function public.travel_admin1_normalize() returns trigger
language plpgsql as $$
begin
  if new.admin1 is not null then
    select a.ko into new.admin1 from travel_admin1_alias a
     where a.country_code = new.country_code and a.raw = new.admin1
    union all select new.admin1 limit 1;
  end if;
  return new;
end $$;
drop trigger if exists trg_travel_admin1_normalize on travel_places;
create trigger trg_travel_admin1_normalize before insert or update of admin1, country_code on travel_places
  for each row execute function public.travel_admin1_normalize();

-- 6) 한국어끼리 표기만 다른 같은 지역 합치기(도시 vs 그 도시를 둘러싼 주는 다른 지역이라 합치지 않는다:
--    부에노스아이레스/부에노스아이레스주, 민스크/민스크주, 알마티/알마티주, 모스크바/모스크바 주, 타슈켄트/타슈켄트주, 비엔티안주/비엔티안도)
insert into travel_admin1_alias(country_code, raw, ko) values
('GR','테살리아','테살리아주'),('MY','크다주','크다'),('SD','나일강','나일강주'),('TW','가오슝','가오슝시'),('FR','옥시타니아','옥시타니')
on conflict (country_code, raw) do update set ko = excluded.ko;
update travel_places p set admin1 = a.ko from travel_admin1_alias a
 where a.country_code = p.country_code and a.raw = p.admin1
   and (a.country_code, a.raw) in (('GR','테살리아'),('MY','크다주'),('SD','나일강'),('TW','가오슝'),('FR','옥시타니아'));
